booklib/views/borrowed.py
from flask import Blueprint, render_template, jsonify

bp = Blueprint("borroweds", __name__, url_prefix="/borroweds")


@bp.route("/")
def index():
    borroweds = [
        {
            "id": 1,
            "receipt_number": "ABCDE12345",
            "book": {
                "id": 1,
                "image_url": (
                    "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com",
                    "/books/1287493789l/179133.jpg",
                ),
                "title": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
                "author": "Evans, Eric",
                "published": "20 Agustus 2003",
                "quantity": 1,
            },
            "student": {"id": 1, "name": "Milch", "number": "ABCDEF"},
            "created_at": "2021-07-01",
            "updated_at": "2021-08-01",
            "returned": 1,
        }
    ]
    return render_template("borrowed/index.html", borroweds=borroweds)


@bp.route("/create")
def create():
    return render_template("borrowed/create.html")


@bp.route("/returned/<int:borrowed_id>")
def returned():
    pass


@bp.route("/delete/<int:borrowed_id>")
def delete():
    pass


@bp.route("/books")
def books_search():
    books = [
        {
            "id": 1,
            "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com"
            "/books/1287493789l/179133.jpg",
            "title": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
            "authors": [{"id": 1, "name": "Evans"}, {"id": 2, "name": "Eric"}],
            "published": "20 Agustus 2003",
            "quantity": 1,
        }
    ]
    return jsonify(books)


@bp.route("/students")
def students_search():
    students = [{"number": "ABCDE1234", "name": "Hammer Code"}]
    return jsonify(students)

booklib/templates/borrowed/create.html
{% extends "base.html" %}
{% block title %}Borrow{% endblock %}
{% block content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Borrowed</h1>
    <div class="">
        <form action="" method="post">
            <div class="block my-2">
                <label for="book" class="w-full">Book</label>
                <input id="book" type="text" name="book"
                    class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <div class=" block my-2">
                <label for="student" class="w-full">Student</label>
                <input id="student" type="text" name="student"
                    class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-md my-2">
                Save
            </button>
        </form>
    </div>
</section>
<script>
    document.getElementById("book").addEventListener("input", function (e) {
        renderSuggestions(this, "bookSuggestions", "/borroweds/books?title=", "title", "book-suggestion")
    })
    document.getElementById("student").addEventListener("input", function (e) {
        renderSuggestions(this, "studentSuggestions", "/borroweds/students?number=", "number", "student-suggestion")
    })

    function renderSuggestions(inputEl, suggestionId, fetchUrl, ref, refId) {
        deleteSuggestions(refId)
        const suggestionsExist = document.getElementById(suggestionId)
        if (!suggestionsExist) {
            const suggestions = document.createElement("div")
            suggestions.setAttribute("class", "w-full")
            suggestions.setAttribute("id", suggestionId)
            inputEl.parentNode.appendChild(suggestions)
        }
        const suggestions = document.getElementById(suggestionId)
        fetch(`${fetchUrl}${inputEl.value}`)
            .then(response => response.json())
            .then((data) => {
                for (let i = 0; i < data.length; i++) {
                    const dataList = document.createElement("div")
                    dataList.setAttribute("class", "w-full py-2 px-2 border border-black " + refId)
                    dataList.addEventListener("click", function () {
                        inputEl.value = this.innerHTML
                        deleteSuggestions(refId)
                    })
                    dataList.innerHTML = data[i][ref]
                    suggestions.appendChild(dataList)
                }
            })
    }

    function deleteSuggestions(refId) {
        suggestions = document.getElementsByClassName(refId)
        for (let i = 0; i < suggestions.length; i++) {
            suggestions[i].parentNode.removeChild(suggestions[i])
        }
    }
</script>
{% endblock %}

booklib/templates/borrowed/index.html
{% extends "base.html" %}
{% block title %}Borrowed{% endblock %}
{% block content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Data Book Borrowed</h1>
    <a class="px-4 py-2 bg-blue-500 rounded text-white" href="{{ url_for('borroweds.create') }}">Borrow new</a>
    <table class="mt-5 table-auto w-full border-collapse border border-black">
        <thead>
            <tr>
                <th class="border border-black">#</th>
                <th class="border border-black">Receipt</th>
                <th class="border border-black">Title</th>
                <th class="border border-black">Student</th>
                <th class="border border-black">Borrowed</th>
                <th class="border border-black">Returned</th>
                <th class="border border-black">Action</th>
            </tr>
        </thead>
        <tbody id="list">
            {% if borroweds %}
            {% for borrowed in borroweds %}
            <tr>
                <td class="text-center border border-black">{{ loop.index }}</td>
                <td class="text-center border border-black">
                    {{ borrowed.receipt_number }}
                </td>
                <td class="border border-black px-2">{{ borrowed.book.title }}</td>
                <td class="border border-black px-2">{{ borrowed.student.name }}</td>
                <td class="border border-black px-2 text-center">
                    {{ borrowed.created_at }}
                </td>
                <td class="border border-black px-2 text-center">
                    {% if borrowed.returned %}
                    {{ borrowed.updated_at }}
                    {% endif %}
                </td>
                <td class="border border-black px-2">
                    <button class="text-blue-500" onclick="handleReturn(event, {{ borrowed.id }})">
                        Return
                    </button>
                    <button class="text-red-500" onclick="handleDelete(event, {{ borrowed.id }})">
                        Delete
                    </button>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td class="border border-black px-2 text-center" colspan="6">
                    Data is empty
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</section>
<script>
    const handleReturn = function (e, id) {
        const tr = e.target.parentNode.parentNode;
        if (!confirm("Are you sure you want to return this?")) {
            return;
        }

        const form = document.createElement("form");
        form.id = "returned";
        form.action = `/borroweds/returned/${id}`;
        form.method = "post";
        document.body.appendChild(form);
        document.getElementById("returned").submit();
    };

    const handleDelete = function (e, id) {
        const list = document.getElementById("list");
        const tr = e.target.parentNode.parentNode;
        if (!confirm("Are you sure you want to delete this?")) {
            return;
        }

        const form = document.createElement("form");
        form.id = "delete";
        form.action = `/borroweds/delete/${id}`;
        form.method = "post";
        document.body.appendChild(form);
        document.getElementById("delete").submit();
    };
</script>
{% endblock %}