booklib/views/book.py
import os
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    current_app as app,
)
from werkzeug.utils import secure_filename
from booklib.repositories import BookRepository, AuthorRepository
from booklib.utils import generate_random_string, allowed_file, get_extension

bp = Blueprint("books", __name__, url_prefix="/books")
book_repo = BookRepository()
author_repo = AuthorRepository()


@bp.route("/")
def index():
    books = book_repo.get_all()
    return render_template("book/index.html", books=books)


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        title = request.form["title"]
        authors = request.form.getlist("authors")
        published = request.form["published"]
        quantity = request.form["quantity"]

        if not title:
            flash("Title is required", "error")

        author_empty = sum([1 if author == "" else 0 for author in authors])
        if len(authors) == author_empty:
            flash("Author is required", "error")
        if not published:
            flash("Published is required", "error")
        if not quantity:
            flash("Quantity is required", "error")
        if "image" not in request.files:
            flash("Image is required", "error")
        else:
            image_file = request.files["image"]
            if image_file.filename == "":
                flash("Image is required", "error")
            if image_file and allowed_file(
                image_file.filename, {"png", "jpg", "jpeg", "gif"}
            ):
                filename = secure_filename(image_file.filename)
                image_url = ".".join(
                    [generate_random_string(16), get_extension(filename)]
                )
                folder_path = "".join([app.config["UPLOAD_FOLDER"], "/book/"])
                image_file.save(os.path.join(folder_path, image_url))
        if not (
            title
            and published
            and quantity
            and len(authors) == author_empty
            and image_file in request.files
        ):
            book_repo.create(
                {
                    "title": title,
                    "published": published,
                    "quantity": quantity,
                    "image_url": image_url,
                    "authors": authors,
                }
            )
            flash("Book is created", "success")
            return redirect("/books")
    authors = author_repo.get_all_select(("id", "name"))
    return render_template("book/create.html", authors=authors)


@bp.route("/edit/<int:book_id>", methods=["GET", "POST"])
def edit(book_id):
    book = book_repo.filter_by_id(book_id)
    if request.method == "POST":
        image_exists = False
        title = request.form["title"]
        authors = request.form.getlist("authors")
        published = request.form["published"]
        quantity = request.form["quantity"]
        if not title:
            flash("Title is required", "error")
        author_empty = sum([1 if author == "" else 0 for author in authors])
        if len(authors) == author_empty:
            flash("Author is required", "error")
        if not published:
            flash("Published is required", "error")
        if not quantity:
            flash("Quantity is required", "error")
        if "image" in request.files:
            image_file = request.files["image"]
            if (
                image_file.filename != ""
                and image_file
                and allowed_file(image_file.filename, {"png", "jpg", "jpeg", "gif"})
            ):
                filename = secure_filename(image_file.filename)
                image_url = ".".join(
                    [generate_random_string(16), get_extension(filename)]
                )
                folder_path = "".join([os.getenv("UPLOAD_FOLDER"), "/book/"])
                image_file.save(os.path.join(folder_path, image_url))
                os.remove(
                    "".join([os.getenv("UPLOAD_FOLDER"), "/book/", book["image_url"]])
                )
                image_exists = True
        if not (title and published and quantity and len(authors) == author_empty):
            data = {
                "title": title,
                "published": published,
                "quantity": quantity,
                "authors": authors,
            }
            if image_exists:
                data["image_url"] = image_url
            book = book_repo.update(book_id, data)
            flash("Book is updated", "success")
            return redirect("/books")
    authors = author_repo.get_all_select(("id", "name"))
    return render_template("book/edit.html", book=book, authors=authors)


@bp.route("/delete/<int:book_id>", methods=["POST"])
def delete(book_id):
    book = book_repo.filter_by_id(book_id)
    os.remove("".join([app.config["UPLOAD_FOLDER"], "/book/", book["image_url"]]))
    book_repo.delete(book_id)
    flash("Book is deleted", "success")
    return redirect("/books")


@bp.route("/image_display/<filename>")
def image_display(filename):
    return redirect(
        url_for("static", filename="".join(["upload/book/", filename])), code=301
    )

booklib/templates/book/create.html
{% extends "base.html" %} {% block title %}Books Create{% endblock %} {% block
content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Create Book</h1>
    <div class="">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="block my-2">
                <label for="name" class="w-full">Title</label>
                <input type="text" name="title" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <div class="block my-2">
                <label for="authors" class="w-full">Author</label>
                <div id="authorsWrapper">
                    <div class="flex w-full items-center">
                        <select name="authors" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2">
                            <option value=""></option>
                            {% for author in authors %}
                            <option value="{{ author.id }}">{{ author.name }}</option>
                            {% endfor %}
                        </select>
                        <a href="#" class="px-2 text-green-400" onclick="addAuthorField()">
                            +
                        </a>
                    </div>
                </div>
            </div>
            <div class="block my-2">
                <label for="published" class="w-full">Published</label>
                <input type="date" name="published" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <div class="block my-2">
                <label for="quantity" class="w-full">Quantity</label>
                <input type="number" name="quantity" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <div class="block my-2">
                <label for="image" class="w-full">Image</label>
                <input type="file" name="image" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-md my-2">
                Save
            </button>
        </form>
    </div>
</section>
<script type="text/javascript">
    const authors = {{ authors| safe }};

    const addAuthorField = () => {
        const authorWrapper = document.getElementById("authorsWrapper");
        const authorCount = authorWrapper.children.length;
        const authorDiv = document.createElement("div");
        authorDiv.id = `author_${authorCount}`;
        authorDiv.classList = "flex w-full items-center";
        const authorAnchor = document.createElement("a");
        authorAnchor.href = "#";
        authorAnchor.classList = "px-2 text-red-400";
        authorAnchor.text = "-";
        authorAnchor.addEventListener("click", () => {
            removeAuthorFields(authorCount);
        })
        const authorSelect = document.createElement("select");
        authorSelect.classList = "w-full border border-blue-500 rounded-md py-1 px-2 my-2";
        authorSelect.name = "authors";
        const emptyOption = document.createElement("option");
        authorSelect.appendChild(emptyOption);
        authors.map((author) => {
            authorOption = document.createElement("option");
            authorOption.value = author.id;
            authorOption.text = author.name;
            authorSelect.appendChild(authorOption);
        })
        authorDiv.appendChild(authorSelect);
        authorDiv.appendChild(authorAnchor);
        authorWrapper.appendChild(authorDiv);
    }

    const removeAuthorFields = (id) => {
        const div = document.getElementById(`author_${id}`)
        div.parentNode.removeChild(div);
    }
</script>
{% endblock %}

booklib/templates/book/edit.html
{% extends "base.html" %} {% block title %}Books Edit{% endblock %} {% block
content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Edit Book</h1>
    <div class="">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="block my-2">
                <label for="name" class="w-full">Title</label>
                <input type="text" name="title" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
                    value="{{ book.title }}" />
            </div>
            <div class="block my-2">
                <label for="authors" class="w-full">Author</label>
                <div id="authorsWrapper">
                    {% for book_author in book.authors %} {% if loop.first %}
                    <div class="flex w-full items-center">
                        <select name="authors" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2">
                            <option value=""></option>
                            {% for author in authors %}
                            <option value="{{ author.id }}" {% if author.id==book_author.id %} selected {% endif %}>{{
                                author.name }}</option>
                            {% endfor %}
                        </select>
                        <a href="#" class="px-2 text-green-400" onclick="addAuthorField()">
                            +
                        </a>
                    </div>
                    {% else %}
                    <div class="flex w-full items-center" id="author_{{ loop.index }}">
                        <select name="authors" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2">
                            <option value=""></option>
                            {% for author in authors %}
                            <option value="{{ author.id }}" {% if author.id==book_author.id %} selected {% endif %}>{{
                                author.name }}</option>
                            {% endfor %}
                        </select>
                        <a href="#" class="px-2 text-red-400" onclick="removeAuthorFields({{ loop.index }})">
                            -
                        </a>
                    </div>
                    {% endif %} {% endfor %}
                </div>
            </div>
            <div class="block my-2">
                <label for="published" class="w-full">Published</label>
                <input type="date" name="published" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
                    value="{{ book.published }}" />
            </div>
            <div class="block my-2">
                <label for="quantity" class="w-full">Quantity</label>
                <input type="number" name="quantity" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
                    value="{{ book.quantity }}" />
            </div>
            <div class="block my-2">
                <img src="{{ url_for('books.image_display', filename=book.image_url) }}" alt="{{ book.title }}">
            </div>
            <div class="block my-2">
                <label for="image" class="w-full">Image</label>
                <input type="file" name="image" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-md my-2">
                Edit
            </button>
        </form>
    </div>
</section>
<script type="text/javascript">
    const authors = {{ authors| safe }};

    const addAuthorField = () => {
        const authorWrapper = document.getElementById("authorsWrapper");
        const authorCount = authorWrapper.children.length;
        const authorDiv = document.createElement("div");
        authorDiv.id = `author_${authorCount}`;
        authorDiv.classList = "flex w-full items-center";
        const authorAnchor = document.createElement("a");
        authorAnchor.href = "#";
        authorAnchor.classList = "px-2 text-red-400";
        authorAnchor.text = "-";
        authorAnchor.addEventListener("click", () => {
            removeAuthorFields(authorCount);
        })
        const authorSelect = document.createElement("select");
        authorSelect.classList = "w-full border border-blue-500 rounded-md py-1 px-2 my-2";
        authorSelect.name = "authors";
        const emptyOption = document.createElement("option");
        authorSelect.appendChild(emptyOption);
        authors.map((author) => {
            authorOption = document.createElement("option");
            authorOption.value = author.id;
            authorOption.text = author.name;
            authorSelect.appendChild(authorOption);
        })
        authorDiv.appendChild(authorSelect);
        authorDiv.appendChild(authorAnchor);
        authorWrapper.appendChild(authorDiv);
    }

    const removeAuthorFields = (id) => {
        const div = document.getElementById(`author_${id}`)
        div.parentNode.removeChild(div);
    }
</script>
{% endblock %}

booklib/templates/book/index.html
{% extends "base.html" %} {% block title %}Books{% endblock %} {% block content
%}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Data Book</h1>
    <a class="px-4 py-2 bg-blue-500 rounded text-white" href="{{ url_for('books.create') }}">Add new</a>
    <table class="mt-5 table-auto w-full border-collapse border border-black">
        <thead>
            <tr>
                <th class="border border-black">#</th>
                <th class="border border-black">Image</th>
                <th class="border border-black">Title</th>
                <th class="border border-black">Author</th>
                <th class="border border-black">Published</th>
                <th class="border border-black">Quantity</th>
                <th class="border border-black">Action</th>
            </tr>
        </thead>
        <tbody id="list">
            {% if books %} {% for book in books %}
            <tr>
                <td class="text-center border border-black">{{ loop.index }}</td>
                <td class="border border-black px-2 text-center">
                    <img class="w-32" src="{{ url_for('books.image_display', filename=book.image_url) }}"
                        alt="{{ book.title }}" />
                </td>
                <td class="border border-black px-2">{{ book.title }}</td>
                <td class="border border-black px-2">
                    {% for author in book.authors %}{{ author.name }}{% if (not loop.last)
                    %}, {% endif %} {% endfor %}
                </td>
                <td class="border border-black px-2">{{ book.published }}</td>
                <td class="border border-black px-2 text-center">
                    {{ book.quantity }}
                </td>
                <td class="border border-black px-2">
                    <a href="{{ url_for('books.edit', book_id=book.id) }}" class="text-blue-500">Edit</a>
                    <button class="text-red-500" onclick="handleDelete(event, {{ book.id }})">
                        Delete
                    </button>
                </td>
            </tr>
            {% endfor %} {% else %}
            <tr>
                <td class="text-center border border-black px-2" colspan="7">
                    Data is empty
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</section>
<script>
    const handleDelete = function (e, id) {
        const list = document.getElementById("list");
        const tr = e.target.parentNode.parentNode;
        if (!confirm("Are you sure you want to delete this?")) {
            return;
        }

        const form = document.createElement("form");
        form.id = "delete";
        form.action = `/books/delete/${id}`;
        form.method = "post";
        document.body.appendChild(form);
        document.getElementById("delete").submit();
    };
</script>
{% endblock %}