booklib/views/author.py
from flask import Blueprint, render_template, request, redirect, flash
from booklib.repositories import AuthorRepository


bp = Blueprint("authors", __name__, url_prefix="/authors")
author_repo = AuthorRepository()


@bp.route("/")
def index():
    authors = author_repo.get_all()
    return render_template("author/index.html", authors=authors)


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        name = request.form["name"]
        if not name:
            flash("Name is required", "error")
        if name:
            author_repo.create({"name": name})
            flash("Author is created", "success")
            return redirect("/authors")
    return render_template("author/create.html")


@bp.route("/edit/<int:author_id>", methods=["GET", "POST"])
def edit(author_id):
    if request.method == "POST":
        name = request.form["name"]
        if not name:
            flash("Name is required", "error")
        if name:
            author_repo.update(author_id, {"name": name})
            flash("Author is updated", "success")
            return redirect("/authors")
    author = author_repo.filter_by_id(author_id)
    return render_template("author/edit.html", author=author)


@bp.route("/delete/<int:author_id>", methods=["POST"])
def delete(author_id):
    author_repo.delete(author_id)
    flash("Author is deleted", "success")
    return redirect("/authors")

booklib/templates/author/create.html
{% extends "base.html" %} {% block title %}Authors Create{% endblock %} {% block
content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Create Author</h1>
    <div class="">
        <form action="" method="post">
            <div class="block my-2">
                <label for="name" class="w-full">Name</label>
                <input type="text" name="name" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2" />
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-md my-2">
                Save
            </button>
        </form>
    </div>
</section>
{% endblock %}

booklib/templates/author/edit.html
{% extends "base.html" %}
{% block title %}Authors Edit{% endblock %}
{% block content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Edit Author</h1>
    <div class="">
        <form action="" method="post">
            <div class="block my-2">
                <label for="name" class="w-full">Name</label>
                <input type="text" name="name" class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
                    value="{{ author.name }}" />
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded-md my-2">
                Edit
            </button>
        </form>
    </div>
</section>
{% endblock %}

booklib/templates/author/index.html
{% extends "base.html" %} {% block title %}Authors{% endblock %} {% block
content %}
<section>
    <h1 class="text-center font-bold text-2xl mb-5">Data Authors</h1>
    <a class="px-4 py-2 bg-blue-500 rounded text-white" href="{{ url_for('authors.create') }}">Add new</a>
    <table class="mt-5 table-auto w-full border-collapse border border-black">
        <thead>
            <tr>
                <th class="border border-black">#</th>
                <th class="border border-black">Name</th>
                <th class="border border-black">Action</th>
            </tr>
        </thead>
        <tbody id="list">
            {% if authors %} {% for author in authors %}
            <tr>
                <td class="text-center border border-black">{{ loop.index }}</td>
                <td class="border border-black px-2">{{ author.name }}</td>
                <td class="border border-black px-2">
                    <a href="{{ url_for('authors.edit', author_id=author.id) }}" class="text-blue-500">Edit</a>
                    <button class="text-red-500" onclick="handleDelete(event, {{ author.id }})">
                        Delete
                    </button>
                </td>
            </tr>
            {% endfor %} {% else %}
            <tr>
                <td class="border border-black px-2 text-center" colspan="3">
                    Data is empty
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</section>
<script>
    const handleDelete = function (e, id) {
        const list = document.getElementById("list");
        const tr = e.target.parentNode.parentNode;
        if (!confirm("Are you sure you want to delete this?")) {
            return;
        }

        const form = document.createElement("form");
        form.id = "delete";
        form.action = `/authors/delete/${id}`;
        form.method = "post";
        document.body.appendChild(form);
        document.getElementById("delete").submit();
    };
</script>
</script>
{% endblock %}