booklib/views/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    current_app as app,
    session,
    g,
)
from booklib.repositories import UserRepository, StudentRepository
from booklib.utils.auth import is_guest, is_authenticated


bp = Blueprint("auth", __name__, url_prefix="/auth")
user_repo = UserRepository()
student_repo = StudentRepository()


@bp.route("/register", methods=["GET", "POST"])
@is_guest
def register():
    if request.method == "POST":
        student_name = request.form["name"]
        student_number = request.form["number"]
        password = request.form["password"]
        if not student_name:
            flash("Student name is required", "error")
        if not student_number:
            flash("Student number is required", "error")
        if not password:
            flash("Password is required", "error")
        if student_name and student_number and password:
            user_exists = user_repo.filter_by({"username": student_number})
            if not user_exists:
                user = user_repo.create(
                    {
                        "username": student_number,
                        "password": app.bcrypt.generate_password_hash(password).decode(
                            "utf-8"
                        ),
                        "role": "student",
                    }
                )
                student_repo.create(
                    {
                        "user_id": user["id"],
                        "name": student_name,
                        "number": student_number,
                    }
                )
                flash("You are registered!", "success")
                session["user_id"] = user["id"]
                if user["role"] == "student":
                    return redirect("/my_library")
                elif user["role"] == "admin":
                    return redirect("/borroweds")
            flash("Student already exists", "error")
    return render_template("auth/register.html")


@bp.route("/login", methods=["GET", "POST"])
@is_guest
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        if not username:
            flash("Username is required", "error")
        if not password:
            flash("Password is required", "error")
        if username and password:
            attempted_user = user_repo.filter_by({"username": username})
            if attempted_user:
                attempted_user = attempted_user[0]
                password_check = app.bcrypt.check_password_hash(
                    attempted_user["password"], password
                )
                if password_check:
                    flash(
                        "{} are successfully logged in!".format(
                            attempted_user["username"]
                        ),
                        "success",
                    )
                    session["user_id"] = attempted_user["id"]
                    if attempted_user["role"] == "student":
                        return redirect("/my_library")
                    elif attempted_user["role"] == "admin":
                        return redirect("/borroweds")
            flash("Username or password false", "error")
    return render_template("auth/login.html")


@bp.route("/logout", methods=["GET", "POST"])
@is_authenticated
def logout():
    g.pop("user", None)
    session.pop("user_id", None)
    return redirect("/auth/login")

booklib/views/author.py
from flask import Blueprint, render_template, request, redirect, flash
from booklib.repositories import AuthorRepository


bp = Blueprint("authors", __name__, url_prefix="/authors")
author_repo = AuthorRepository()


@bp.route("/")
def index():
    authors = author_repo.get_all()
    return render_template("author/index.html", authors=authors)


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        name = request.form["name"]
        if not name:
            flash("Name is required", "error")
        if name:
            author_repo.create({"name": name})
            flash("Author is created", "success")
            return redirect("/authors")
    return render_template("author/create.html")


@bp.route("/edit/<int:author_id>", methods=["GET", "POST"])
def edit(author_id):
    if request.method == "POST":
        name = request.form["name"]
        if not name:
            flash("Name is required", "error")
        if name:
            author_repo.update(author_id, {"name": name})
            flash("Author is updated", "success")
            return redirect("/authors")
    author = author_repo.filter_by_id(author_id)
    return render_template("author/edit.html", author=author)


@bp.route("/delete/<int:author_id>", methods=["POST"])
def delete(author_id):
    author_repo.delete(author_id)
    flash("Author is deleted", "success")
    return redirect("/authors")

booklib/views/book.py
import os
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
    current_app as app,
)
from werkzeug.utils import secure_filename
from booklib.repositories import BookRepository, AuthorRepository
from booklib.utils import generate_random_string, allowed_file, get_extension

bp = Blueprint("books", __name__, url_prefix="/books")
book_repo = BookRepository()
author_repo = AuthorRepository()


@bp.route("/")
def index():
    books = book_repo.get_all()
    return render_template("book/index.html", books=books)


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        title = request.form["title"]
        authors = request.form.getlist("authors")
        published = request.form["published"]
        quantity = request.form["quantity"]

        if not title:
            flash("Title is required", "error")

        author_empty = sum([1 if author == "" else 0 for author in authors])
        if len(authors) == author_empty:
            flash("Author is required", "error")
        if not published:
            flash("Published is required", "error")
        if not quantity:
            flash("Quantity is required", "error")
        if "image" not in request.files:
            flash("Image is required", "error")
        else:
            image_file = request.files["image"]
            if image_file.filename == "":
                flash("Image is required", "error")
            if image_file and allowed_file(
                image_file.filename, {"png", "jpg", "jpeg", "gif"}
            ):
                filename = secure_filename(image_file.filename)
                image_url = ".".join(
                    [generate_random_string(16), get_extension(filename)]
                )
                folder_path = "".join([app.config["UPLOAD_FOLDER"], "/book/"])
                image_file.save(os.path.join(folder_path, image_url))
        if not (
            title
            and published
            and quantity
            and len(authors) == author_empty
            and image_file in request.files
        ):
            book_repo.create(
                {
                    "title": title,
                    "published": published,
                    "quantity": quantity,
                    "image_url": image_url,
                    "authors": authors,
                }
            )
            flash("Book is created", "success")
            return redirect("/books")
    authors = author_repo.get_all_select(("id", "name"))
    return render_template("book/create.html", authors=authors)


@bp.route("/edit/<int:book_id>", methods=["GET", "POST"])
def edit(book_id):
    book = book_repo.filter_by_id(book_id)
    if request.method == "POST":
        image_exists = False
        title = request.form["title"]
        authors = request.form.getlist("authors")
        published = request.form["published"]
        quantity = request.form["quantity"]
        if not title:
            flash("Title is required", "error")
        author_empty = sum([1 if author == "" else 0 for author in authors])
        if len(authors) == author_empty:
            flash("Author is required", "error")
        if not published:
            flash("Published is required", "error")
        if not quantity:
            flash("Quantity is required", "error")
        if "image" in request.files:
            image_file = request.files["image"]
            if (
                image_file.filename != ""
                and image_file
                and allowed_file(image_file.filename, {"png", "jpg", "jpeg", "gif"})
            ):
                filename = secure_filename(image_file.filename)
                image_url = ".".join(
                    [generate_random_string(16), get_extension(filename)]
                )
                folder_path = "".join([os.getenv("UPLOAD_FOLDER"), "/book/"])
                image_file.save(os.path.join(folder_path, image_url))
                os.remove(
                    "".join([os.getenv("UPLOAD_FOLDER"), "/book/", book["image_url"]])
                )
                image_exists = True
        if not (title and published and quantity and len(authors) == author_empty):
            data = {
                "title": title,
                "published": published,
                "quantity": quantity,
                "authors": authors,
            }
            if image_exists:
                data["image_url"] = image_url
            book = book_repo.update(book_id, data)
            flash("Book is updated", "success")
            return redirect("/books")
    authors = author_repo.get_all_select(("id", "name"))
    return render_template("book/edit.html", book=book, authors=authors)


@bp.route("/delete/<int:book_id>", methods=["POST"])
def delete(book_id):
    book = book_repo.filter_by_id(book_id)
    os.remove("".join([app.config["UPLOAD_FOLDER"], "/book/", book["image_url"]]))
    book_repo.delete(book_id)
    flash("Book is deleted", "success")
    return redirect("/books")


@bp.route("/image_display/<filename>")
def image_display(filename):
    return redirect(
        url_for("static", filename="".join(["upload/book/", filename])), code=301
    )

booklib/views/main.py
from flask import Blueprint, render_template

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    books = [
        {
            "id": 1,
            "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com"
            + "/books/1287493789l/179133.jpg",
            "title": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
            "author": "Evans, Eric",
            "published": "20 Agustus 2003",
            "quantity": 1,
        }
    ]
    return render_template("index.html", books=books)


@bp.route("/my_library")
def my_library():
    books = [
        {
            "id": 1,
            "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com"
            + "/books/1287493789l/179133.jpg",
            "title": "Domain-Driven Design: Tackling Complexity in the Heart of Software",
            "author": "Evans, Eric",
            "published": "20 Agustus 2003",
            "status": "Dikembalikan",
        }
    ]
    return render_template("my_library.html", books=books)

booklib/templates/authors_create.html
{% extends "base.html" %} {% block title %}Authors Create{% endblock %} {% block
content %}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Create Author</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="name" class="w-full">Name</label>
        <input
          type="text"
          name="name"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Save
      </button>
    </form>
  </div>
</section>
{% endblock %}

booklib/templates/authors_edit.html
{% extends "base.html" %} {% block title %}Authors Edit{% endblock %} {% block
content %}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Edit Author</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="name" class="w-full">Name</label>
        <input
          type="text"
          name="name"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
          value="{{ author.name }}"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Edit
      </button>
    </form>
  </div>
</section>
{% endblock %}

booklib/templates/authors_index.html
{% extends "base.html" %} {% block title %}Authors{% endblock %} {% block
content %}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Data Authors</h1>
  <a
    class="px-4 py-2 bg-blue-500 rounded text-white"
    href="{{ url_for('authors_create') }}"
    >Add new</a
  >
  <table class="mt-5 table-auto w-full border-collapse border border-black">
    <thead>
      <tr>
        <th class="border border-black">#</th>
        <th class="border border-black">Name</th>
        <th class="border border-black">Action</th>
      </tr>
    </thead>
    <tbody id="list">
      {% if authors %} {% for author in authors %}
      <tr>
        <td class="text-center border border-black">{{ loop.index }}</td>
        <td class="border border-black px-2">{{ author.name }}</td>
        <td class="border border-black px-2">
          <a
            href="{{ url_for('authors_edit', author_id=author.id) }}"
            class="text-blue-500"
            >Edit</a
          >
          <button
            class="text-red-500"
            onclick="handleDelete(event, {{ author.id }})"
          >
            Delete
          </button>
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td class="border border-black px-2 text-center" colspan="3">
          Data is empty
        </td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</section>
<script>
  const handleDelete = function (e, id) {
    const list = document.getElementById("list");
    const tr = e.target.parentNode.parentNode;
    if (!confirm("Are you sure you want to delete this?")) {
      return;
    }

    fetch(`/authors/delete/${id}`, {
      method: "POST",
    }).then(() => {
      list.removeChild(tr);
      if (list.children.length === 0) {
        const tr = document.createElement("tr");
        const td = document.createElement("td");
        td.classList = "border border-black px-2 text-center";
        td.setAttribute("colspan", 3);
        td.innerHTML = "Data is empty";
        tr.appendChild(td);
        list.appendChild(tr);
      }
    });
  };
</script>
</script>
{% endblock %}

booklib/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} Book Library</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/png" sizes="16x16" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    {% endblock %}
</head>

<body>
    <header>
        <div class="w-full bg-blue-500 text-white">
            <div class="flex items-center justify-between max-w-4xl mx-auto py-5">
                <div class="logo">
                    <a href="{{ url_for('main.index') }}">Book Library</a>
                </div>
                <nav class="nav">
                    <ul>
                        <li class="inline-block">
                            <a href="{{ url_for('main.index') }}">Home</a>
                        </li>
                        {% if g.user and g.user.role == "student" %}
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('main.my_library') }}">My Library</a>
                        </li>
                        {% endif %}
                        {% if g.user and g.user.role == "admin" %}
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('borroweds.index') }}">Borrowed</a>
                        </li>
                        {% endif %}
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('authors.index') }}">Author</a>
                        </li>
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('books.index') }}">Book</a>
                        </li>
                        {% if g.user %}
                        <li class="inline-block ml-4">
                            <form id="logout" action="{{ url_for('auth.logout') }}" method="post">
                                <a href="#" onclick="document.getElementById('logout').submit();">
                                    Logout
                                </a>
                            </form>
                        </li>
                        {% else %}
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="inline-block ml-4">
                            <a href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        {% if g.user %}
        <div class="w-full bg-gray-200">
            <div class="flex items-center justify-end max-w-4xl mx-auto py-2">
                <div>{{ g.user.username }}</div>
            </div>
        </div>
        {% endif %}
    </header>
    <main class="w-full my-10">
        <div class="max-w-4xl px-4 lg:px-0 mx-auto">
            {% block content %}{% endblock %}
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="max-w-4xl px-4 lg:px-0 mx-auto my-5">
            <ul class="w-full">
                {% for category, message in messages %}
                <li class="py-2 px-2 w-full {{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endwith %}
    </main>
    <footer class="w-full text-center my-10">
        &copy; Copyright 2021 by you.
    </footer>
</body>

</html>

booklib/templates/books_create.html
{% extends "base.html" %} {% block title %}Books Create{% endblock %} {% block
content %}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Create Book</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="name" class="w-full">Title</label>
        <input
          type="text"
          name="title"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <div class="block my-2">
        <label for="authors" class="w-full">Author</label>
        <div id="authorsWrapper">
          <div class="flex w-full items-center">
            <select
              name="authors[]"
              class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
            >
              <option value=""></option>
              {% for author in authors %}
              <option value="{{ author.id }}">{{ author.name }}</option>
              {% endfor %}
            </select>
            <a href="#" class="px-2 text-green-400" onclick="addAuthorField()">
              +
            </a>
          </div>
        </div>
      </div>
      <div class="block my-2">
        <label for="published" class="w-full">Published</label>
        <input
          type="date"
          name="published"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <div class="block my-2">
        <label for="quantity" class="w-full">Quantity</label>
        <input
          type="number"
          name="quantity"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <div class="block my-2">
        <label for="image" class="w-full">Image</label>
        <input
          type="file"
          name="image"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Save
      </button>
    </form>
  </div>
</section>
<script type="text/javascript">
  const authors = {{ authors|safe }};
  const addAuthorField= () => {
    const authorWrapper = document.getElementById("authorsWrapper");
    const authorCount = authorWrapper.children.length;
    const authorDiv = document.createElement("div");
    authorDiv.id = `author_${authorCount}`;
    authorDiv.classList = "flex w-full items-center";
    const authorAnchor = document.createElement("a");
    authorAnchor.href = "#";
    authorAnchor.classList = "px-2 text-red-400";
    authorAnchor.text = "-";
    authorAnchor.addEventListener("click", () => {
      removeAuthorFields(authorCount);
    })
    const authorSelect = document.createElement("select");
    authorSelect.classList = "w-full border border-blue-500 rounded-md py-1 px-2 my-2";
    authorSelect.name = "authors[]";
    const emptyOption = document.createElement("option");
    authorSelect.appendChild(emptyOption);
    authors.map((author) => {
      authorOption = document.createElement("option");
      authorOption.value = author.id;
      authorOption.text = author.name;
      authorSelect.appendChild(authorOption);
    })
    authorDiv.appendChild(authorSelect);
    authorDiv.appendChild(authorAnchor);
    authorWrapper.appendChild(authorDiv);
  }

  const removeAuthorFields = (id) => {
    const div = document.getElementById(`author_${id}`)
    div.parentNode.removeChild(div);
  }
</script>
{% endblock %}

booklib/templates/books_edit.html
{% extends "base.html" %} {% block title %}Books Edit{% endblock %} {% block
content %}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Edit Book</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="name" class="w-full">Title</label>
        <input
          type="text"
          name="title"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
          value="{{ book.title }}"
        />
      </div>
      <div class="block my-2">
        <label for="author" class="w-full">Author</label>
        <input
          type="text"
          name="author"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
          value="{{ book.author }}"
        />
      </div>
      <div class="block my-2">
        <label for="published" class="w-full">Published</label>
        <input
          type="date"
          name="published"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
          value="{{ book.published }}"
        />
      </div>
      <div class="block my-2">
        <label for="quantity" class="w-full">Quantity</label>
        <input
          type="number"
          name="quantity"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
          value="{{ book.quantity }}"
        />
      </div>
      <div class="block my-2">
        <label for="image" class="w-full">Image</label>
        <input
          type="file"
          name="image"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Edit
      </button>
    </form>
  </div>
</section>
{% endblock %}

booklib/templates/books_index.html
{% extends "base.html" %} {% block title %}Books{% endblock %} {% block content
%}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Data Book</h1>
  <a
    class="px-4 py-2 bg-blue-500 rounded text-white"
    href="{{ url_for('books_create') }}"
    >Add new</a
  >
  <table class="mt-5 table-auto w-full border-collapse border border-black">
    <thead>
      <tr>
        <th class="border border-black">#</th>
        <th class="border border-black">Image</th>
        <th class="border border-black">Title</th>
        <th class="border border-black">Author</th>
        <th class="border border-black">Published</th>
        <th class="border border-black">Quantity</th>
        <th class="border border-black">Action</th>
      </tr>
    </thead>
    <tbody id="list">
      {% if books %} {% for book in books %}
      <tr>
        <td class="text-center border border-black">{{ loop.index }}</td>
        <td class="border border-black px-2 text-center">
          <img class="w-32" src="{{ book.image_url }}" alt="{{ book.title }}" />
        </td>
        <td class="border border-black px-2">{{ book.title }}</td>
        <td class="border border-black px-2">{{ book.author }}</td>
        <td class="border border-black px-2">{{ book.published }}</td>
        <td class="border border-black px-2 text-center">
          {{ book.quantity }}
        </td>
        <td class="border border-black px-2">
          <a
            href="{{ url_for('books_edit', book_id=book.id) }}"
            class="text-blue-500"
            >Edit</a
          >
          <button
            class="text-red-500"
            onclick="handleDelete(event, {{ book.id }})"
          >
            Delete
          </button>
        </td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td class="text-center border border-black px-2" colspan="7">
          Data is empty
        </td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</section>
<script>
  const handleDelete = function (e, id) {
    const list = document.getElementById("list");
    const tr = e.target.parentNode.parentNode;
    if (!confirm("Are you sure you want to delete this?")) {
      return;
    }

    fetch(`/books/delete/${id}`, {
      method: "POST",
    }).then(() => {
      list.removeChild(tr);
      if (list.children.length === 0) {
        const tr = document.createElement("tr");
        const td = document.createElement("td");
        td.classList = "border border-black px-2 text-center";
        td.setAttribute("colspan", 7);
        td.innerHTML = "Data is empty";
        tr.appendChild(td);
        list.appendChild(tr);
      }
    });
  };
</script>
{% endblock %}

booklib/templates/borrowed_create.html
{% extends "base.html" %} {% block title %}Borrow{% endblock %} {% block content
%}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Borrowed</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="book" class="w-full">Book</label>
        <input
          type="text"
          name="book"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <div class="block my-2">
        <label for="student" class="w-full">Student</label>
        <input
          type="text"
          name="student"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Save
      </button>
    </form>
  </div>
</section>
{% endblock %}

booklib/templates/borroweds_create.html
{% extends "base.html" %} {% block title %}Borrow{% endblock %} {% block content
%}
<section>
  <h1 class="text-center font-bold text-2xl mb-5">Borrowed</h1>
  <div class="">
    <form action="" method="post">
      <div class="block my-2">
        <label for="book" class="w-full">Book</label>
        <input
          type="text"
          name="book"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <div class="block my-2">
        <label for="student" class="w-full">Student</label>
        <input
          type="text"
          name="student"
          class="w-full border border-blue-500 rounded-md py-1 px-2 my-2"
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-md my-2"
      >
        Save
      </button>
    </form>
  </div>
</section>
{% endblock %}

booklib/templates/index.html
{% extends "base.html" %}
{% block title %} {% endblock %}
{% block content %}
<section class="max-w-4xl mx-auto">
    {% if books %}
    {% for book in books %}
    <article class="flex">
        <img class="w-32" src="{{ book.image_url }}" alt="{{ book.title }}" />
        <div class="ml-4">
            <h2 class="font-bold text-2xl">{{ book.title }}</h2>
            <p>Penulis:
                {% for author in book.authors %}
                {{ author.name }}{% if (not loop.last) %}, {% endif %}
                {% endfor%}
            </p>
            <p>Tanggal Terbit: {{ book.published }}</p>
            <p>Jumlah Tersedia: {{ book.quantity }}</p>
        </div>
    </article>
    {% endfor %}
    {% else %}
    <article class="flex">
        <h3 class="w-full text-center text-2xl">Data is empty</h3>
    </article>
    {% endif %}
</section>
{% endblock %}

booklib/templates/my_library.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<section class="max-w-4xl mx-auto">
    {% if borroweds %} {% for borrowed in borroweds %}
    <article class="flex mb-5">
        <img class="w-32" src="{{ url_for('books.image_display', filename=borrowed.book.image_url) }}"
            alt="{{ borrowed.book.title }}" />
        <div class="ml-4">
            <h2 class="font-bold text-2xl">{{ borrowed.book.title }}</h2>
            <p>Penulis:
                {% for author in borrowed.book.authors %}
                {{ author.name }}{% if (not loop.last) %}, {% endif %}
                {% endfor%}
            </p>
            <p>Tanggal Terbit: {{ borrowed.book.published }}</p>
            {% if borrowed.returned %}
            <p class="text-green-500">Dikembalikan</p>
            {% else %}
            <p class="text-yellow-500">Masih dipinjam</p>
            {% endif %}
        </div>
    </article>
    {% endfor %}
    {% else %}
    <article class="flex">
        <h3 class="w-full text-center text-2xl">Data is empty</h3>
    </article>
    {% endif %}
</section>
{% endblock %}